#!/bin/bash

# Load environment variables from .env if present
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -f "$SCRIPT_DIR/.env" ]; then
    set -a
    source "$SCRIPT_DIR/.env"
    set +a
elif [ -f ".env" ]; then
    set -a
    source ".env"
    set +a
fi

export GITHUB_TOKEN="${GITHUB_TOKEN:-}"
export GH_TOKEN="${GH_TOKEN:-$GITHUB_TOKEN}"
export ADMIN_TOKEN="${ADMIN_TOKEN:-$GITHUB_TOKEN}"

if [ -z "$GITHUB_TOKEN" ]; then
    echo "Error: GITHUB_TOKEN is not set. Please define it in .env or as an environment variable."
    exit 1
fi

root_path="C:/Users/ishan/Documents/Projects"

repositories=(
    "Awesome-Vacation-Rental-Management"
    "b13a4ac24c8eb9a550148bde61b3cab3"
    "bar_chart_race_paulodiogo_my"
    "BATMAN-growth"
    "better_bing_image_downloader"
    "Big-Tech-CapEx"
    "Bing_Image_Downloader_Service"
    "Bing_Image_Extension"
    "BRICS-Economics"
    "BRICS-vs-G7-STEM-Talent"
    "Business-Strategy-AI-Agent"
    "CallSilencer_noteworking"
    "CAT-Aspirants-vs-Acceptance"
    "cf-stats-enhancer"
    "chatterbox"
    "Chinas_Performance_in_Science_Olympiads"
    "Chinese-Pops-US-AI-Bubble"
    "claude-agent-orchestration"
    "claude-code-plugins-directory"
    "claude-skills-by-karpathy"
    "claudebot"
    "clineawesome"
    "Code-Knowledge-Graph"
    "Coding-Prompts"
    "CoinsFlow"
    "create-github-repo"
    "crew"
    "CSSFrameworks2024"
    "directory-translator"
    "DOGMA-growth"
    "economics_plots"
    "Embodied-AI-and-Robotics-Tutorials"
    "emoji_extension"
    "Evolution-Of-AI-Budgets"
    "Expoential-Laws"
    "Extract_To_Sheets"
    "FAANG_vs_GCC_ITServices_in_India_Freshers_Hired"
    "FAANG_vs_GCC_ITServices_in_India_Headcount"
    "FAANG-growth"
    "FasterClaw"
    "fetch-github-forkers"
    "filter-github-repo-by-topic"
    "find-unprotected-repo"
    "Follow_Github"
    "Follow_HuggingFace"
    "Forward-Deployed-Engineer-Interview-Questions"
    "Free-AI-Coding-Agents"
    "Free-Claude"
    "Free-GPT"
    "Free-Kimi-K3"
    "Free-Speech-to-Text"
    "gen-cli"
    "gh-browse-or-reload"
    "Github-Analytics"
    "Github-Follower-Analytics"
    "github-protector"
    "github-ranking-web"
    "github-repo-growth"
    "github-shooting-game"
    "Github-Tutorials"
    "Global-Innovation-Index"
    "HDGenerator"
    "how-to-make-a-million-dollars-on-github"
    "HRM-Tutorials"
    "Humanoid-Robots"
    "Hyperlink_Extractor"
    "icloud-downloader"
    "IIT_vs_Private_Engineering_Spending_Per_Student"
    "Image-Denoising-Landscape"
    "image-multisize-resizer"
    "IMO-Hot-Regions"
    "India_Performance_in_Science_Olympiads"
    "India-Can-Surpass-Them-By-2047"
    "India-Data-Center-Capacity"
    "Indian-IT-Headcount"
    "Indian-IT-Salary"
    "Indian-Metros"
    "Infinite-Free-Coding-Rotation-Strategy"
    "Insane-Revenue-Tech-Companies"
    "Insane-Valuation-Tech-Companies"
    "Invite-GitHub-Users"
    "ishandutta2007"
    "ishandutta2007.github.io"
    "ishandutta2007.github.io.old"
    "JEE-Aspirants-vs-Acceptance"
    "JEPA-Tutorial"
    "Karpathys-Claude-Guide"
    "Large-Language-Models-Tutorials"
    "Le-World-Model"
    "Linkedin-Withdraw-Request-Ext"
    "Linkedin-Withdraw-Request-Ext-Pro"
    "List-GitHub-Contributors"
    "List-GitHub-PRs"
    "local-whisper"
    "MAAMA_vs_BATMANSS"
    "manage-github-pull-requests"
    "manage-github-tabs-buttons"
    "manimations"
    "MCP-Tutorials"
    "MIT-Aspirants-vs-Acceptance"
    "multi-search-n-llm-image-downloader"
    "Multimodal-AI-Tutorials"
    "neuralgym"
    "Nexus"
    "Nvidia-Growth"
    "Olympiad-Medalists-IIT-Seats"
    "open-ai-data-flow"
    "open-ai-detect-shoplifter"
    "open-ai-webflow"
    "open-algolia"
    "open-antigravity"
    "open-atlas"
    "open-coder"
    "open-cowork"
    "open-eye"
    "open-grokbot"
    "open-hr"
    "Open-Lovable"
    "open-mem"
    "open-pay"
    "open-podium"
    "open-reasoning"
    "open-runway"
    "open-sales-gpt"
    "open-swarm-ai-agents"
    "open-tunneling"
    "open-wisprflow"
    "open-workflows"
    "OpenLovable.dev"
    "OpenLovableLanding"
    "OpenManus"
    "Physical-AI-Evangelists"
    "Physical-AI-Research-Report"
    "Producthunt-Hunter"
    "Quantization-Aware-Training"
    "Quora-Perplexity-Automator"
    "reach-github-contributors"
    "Regenerative-Medicine-Evangelist"
    "Regenerative-Medicine-Race"
    "Reinforcement-Learning-Using-Numpy"
    "rem-wm"
    "robot"
    "Robotic-Arm-Mini"
    "rockstar.dev"
    "SaaS_vs_Big_AI_Labs"
    "save-gsheet-to-files"
    "Silicon-Valley-Tech-Hubs"
    "sliding-puzzle"
    "SongLife"
    "Speech-Denoising-Landscape"
    "Speech-to-Text-Landscape"
    "speedupmac"
    "star-history-user"
    "Startup-Funds-IRR"
    "sublime-rust-cpu"
    "sublime-rust-gpu"
    "swachh-bharat"
    "Tab_Text_Paster"
    "Tech-Market-Size-and-Market-Share"
    "tech-writer"
    "Text-to-Speech-Landscape"
    "The-Great-Economic-Convergence"
    "theglobaleconomy-enhancer"
    "Top-AI-repos"
    "Top-AI-Research-Papers"
    "Top-Low-Code"
    "Top-open-source-AI-agents"
    "Top-open-source-blockchain-projects"
    "Top-RnD-Spenders"
    "Tops-of-Github"
    "Trending-Jobs"
    "turboquant"
    "ultimate-watermark-remover-gui"
    "Unfollow_Github"
    "USAs_Performance_in_Science_Olympiads"
    "uttt"
    "veo_prompts"
    "Video-Generation-Landscape"
    "Vision-Language-Action"
    "VoiceSearchFromAddressBar"
    "voronoi"
    "vscodium"
    "watermark-removal"
    "Watermark-Removal-Pytorch"
    "Webchat_to_CLI"
    "Western-Tech-Vs-Chinese-Challenger"
    "wikiedits"
    "windows-cleaner"
    "YCScraper"
    "YoutubeAdSkipper"
    "YoutubeData"
    "YouTubeKeywordHider"
    "ziap.github.io"
    "Awesome-Zero-Trust-Network-Access"
)

for repo in "${repositories[@]}"; do
    echo "========================================"
    echo "Processing: $repo"
    echo "========================================"
    
    # Safely navigate to the directory; skip to the next loop iteration if it fails
    cd "$root_path/$repo" || { 
        echo "Error: Directory $root_path/$repo does not exist. Skipping."
        continue 
    }
    
    echo "Entered: $repo"
    echo "ADMIN_TOKEN: $ADMIN_TOKEN"
    # Execute your commands
    git pull
    github-tabs --token "$ADMIN_TOKEN" Discussions ishandutta2007 "$repo"
    git pull
done

echo "All repositories processed!"
